<?php

return [
    'whatsapp' => [
        'api_url' => env('WHATSAPP_API_URL'),
        'api_token' => env('WHATSAPP_API_TOKEN'),
        'phone_number_id' => env('WHATSAPP_PHONE_NUMBER_ID'),
        'invite_template' => env('WHATSAPP_INVITE_TEMPLATE'),
        'invite_template_lang' => env('WHATSAPP_INVITE_TEMPLATE_LANG', 'ar'),
    ],

    'categories' => [
        'announcements' => ['admin_announcement'],
        'academic' => [
            'assignment_deadline',
            'assignment_submission_reminder',
            'project_assigned',
            'project_teammate_joined',
            'project_team_completed',
            'project_change_requested',
            'project_change_decided',
            'exam_upcoming',
            'session_upcoming',
            'grade_posted',
            'new_lecture_content',
            'assignment_needs_grading',
            'below_passing_grade',
            'attendance_absent_streak',
            'session_unclosed',
            'course_graduation_announced',
            'service_progression_applied',
            'church_cycle_promotion_season',
            'role_assigned',
            'profile_photo_pending_review',
            'profile_photo_reupload_reminder',
        ],
        'events' => [
            'event_nearby',
            'event_new_reservable',
            'event_reservation_cancelled',
        ],
        'pastoral' => [
            'appointment_booking_confirmed',
            'appointment_booking_updated',
            'appointment_booking_cancelled',
            'appointment_booking_rescheduled',
            'appointment_booking_reminder',
        ],
        'social' => ['birthday_today'],
        'reminders' => ['custom_reminder'],
    ],

    'types' => [
        'admin_announcement' => [
            'label' => 'notifications.types.admin_announcement',
            'category' => 'announcements',
            'audience' => ['student', 'instructor', 'admin'],
            'mandatory' => true,
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'birthday_today' => [
            'label' => 'notifications.types.birthday_today',
            'category' => 'social',
            'audience' => ['student', 'instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => false,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'assignment_deadline' => [
            'label' => 'notifications.types.assignment_deadline',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => ['lead_hours' => 24],
            ],
        ],
        'assignment_submission_reminder' => [
            'label' => 'notifications.types.assignment_submission_reminder',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'project_assigned' => [
            'label' => 'notifications.types.project_assigned',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'project_teammate_joined' => [
            'label' => 'notifications.types.project_teammate_joined',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'project_team_completed' => [
            'label' => 'notifications.types.project_team_completed',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'project_change_requested' => [
            'label' => 'notifications.types.project_change_requested',
            'category' => 'academic',
            'audience' => ['instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'project_change_decided' => [
            'label' => 'notifications.types.project_change_decided',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'exam_upcoming' => [
            'label' => 'notifications.types.exam_upcoming',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => ['lead_hours' => 24],
            ],
        ],
        'session_upcoming' => [
            'label' => 'notifications.types.session_upcoming',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => ['lead_hours' => 24],
            ],
        ],
        'grade_posted' => [
            'label' => 'notifications.types.grade_posted',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'new_lecture_content' => [
            'label' => 'notifications.types.new_lecture_content',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => false,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'event_nearby' => [
            'label' => 'notifications.types.event_nearby',
            'category' => 'events',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => false,
                'whatsapp_enabled' => false,
                'config' => ['lead_days' => 7],
            ],
        ],
        'event_new_reservable' => [
            'label' => 'notifications.types.event_new_reservable',
            'category' => 'events',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'attendance_absent_streak' => [
            'label' => 'notifications.types.attendance_absent_streak',
            'category' => 'academic',
            'audience' => ['instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => ['sessions_lookback' => 3],
            ],
        ],
        'session_unclosed' => [
            'label' => 'notifications.types.session_unclosed',
            'category' => 'academic',
            'audience' => ['instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => ['unclosed_days' => 7],
            ],
        ],
        'assignment_needs_grading' => [
            'label' => 'notifications.types.assignment_needs_grading',
            'category' => 'academic',
            'audience' => ['instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'event_reservation_cancelled' => [
            'label' => 'notifications.types.event_reservation_cancelled',
            'category' => 'events',
            'audience' => ['instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => false,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'below_passing_grade' => [
            'label' => 'notifications.types.below_passing_grade',
            'category' => 'academic',
            'audience' => ['instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'custom_reminder' => [
            'label' => 'notifications.types.custom_reminder',
            'category' => 'reminders',
            'audience' => ['student', 'instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'course_application_submitted' => [
            'label' => 'notifications.types.course_application_submitted',
            'category' => 'academic',
            'audience' => ['admin', 'instructor'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'profile_photo_pending_review' => [
            'label' => 'notifications.types.profile_photo_pending_review',
            'category' => 'academic',
            'audience' => ['admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'profile_photo_reupload_reminder' => [
            'label' => 'notifications.types.profile_photo_reupload_reminder',
            'category' => 'academic',
            'audience' => ['student'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'course_graduation_announced' => [
            'label' => 'notifications.types.course_graduation_announced',
            'category' => 'academic',
            'audience' => ['admin', 'instructor'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => false,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'service_progression_applied' => [
            'label' => 'notifications.types.service_progression_applied',
            'category' => 'academic',
            'audience' => ['admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => false,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'church_cycle_promotion_season' => [
            'label' => 'notifications.types.church_cycle_promotion_season',
            'category' => 'academic',
            'audience' => ['admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => false,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'role_assigned' => [
            'label' => 'notifications.types.role_assigned',
            'category' => 'academic',
            'audience' => ['student', 'instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => true,
                'config' => [],
            ],
        ],
        'appointment_booking_confirmed' => [
            'label' => 'notifications.types.appointment_booking_confirmed',
            'category' => 'pastoral',
            'audience' => ['student', 'instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'appointment_booking_updated' => [
            'label' => 'notifications.types.appointment_booking_updated',
            'category' => 'pastoral',
            'audience' => ['student', 'instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => false,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'appointment_booking_cancelled' => [
            'label' => 'notifications.types.appointment_booking_cancelled',
            'category' => 'pastoral',
            'audience' => ['student', 'instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'appointment_booking_rescheduled' => [
            'label' => 'notifications.types.appointment_booking_rescheduled',
            'category' => 'pastoral',
            'audience' => ['student', 'instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => [],
            ],
        ],
        'appointment_booking_reminder' => [
            'label' => 'notifications.types.appointment_booking_reminder',
            'category' => 'pastoral',
            'audience' => ['student', 'instructor', 'admin'],
            'defaults' => [
                'portal_enabled' => true,
                'email_enabled' => true,
                'whatsapp_enabled' => false,
                'config' => ['lead_hours' => 24],
            ],
        ],
    ],
];
