name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.VPS_PATH }}
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            sudo chown -R www-data:www-data ${{ secrets.VPS_PATH }}
            sudo chmod -R 775 ${{ secrets.VPS_PATH }}/storage
            sudo systemctl restart apache2
